apiVersion: v1
Kind: ConfigMap
metadata:
  name: config
data:
  # TEST: openssl req -x509 -newkey rsa:4096 -keyout cert/key.pem -out cert/cert.pem -days 365 -nodes
  TLS_CERT_PATH: cert/cert.pem
  TLS_KEY_PATH: cert/key.pem
  UPSTREAM_ADDR: 127.0.0.1:8000
  BIND_ADDR: 0.0.0.0:443
---
apiVersion: v1
kind: Pod
metadata:
  name: chat-server
spec:
  volumes:
    - name: cert
      hostPath:
        path: cert
        type: Directory

  containers:
    - name: e2ee_chat_server
      image: e2ee_chat_server

    - name: e2ee_chat_ingress
      image: e2ee_chat_ingress
      envFrom:
        - configMapRef:
            name: config
      ports:
        - containerPort: 443
          hostPort: 443
      volumeMounts:
        - mountPath: /app/cert
          name: cert
