apiVersion: v1
Kind: ConfigMap
metadata:
  name: config
data:

---
apiVersion: v1
kind: Pod
metadata:
  name: chat-server
spec:
  volumes:
    - name: tls
      hostPath:
        path: tls
        type: Directory

  containers:
    - name: e2ee_chat_server
      image: e2ee_chat_server
      args:
        [
          "-c",
          "/app/tls/server.crt",
          "-k",
          "/app/tls/server.key",
          "0.0.0.0:443",
        ]
      volumeMounts:
        - mountPath: /app/tls
          name: tls
